### PR TITLE
Refactor & Feature to pull list of all contributors of an organization

### PR DESCRIPTION
**Pull request by arsulegai**

### CODE REVIEW

**Comment by arsulegai** [comment]
@ryjones post this PR, the repository requires PAT to be added for github flows to function.

**Comment by ryjones** [comment]
@arsulegai which repo needs the PAT?

**Comment by arsulegai** [comment]
> @arsulegai which repo needs the PAT?

The current repo https://github.com/hyperledger-tooling/github-contributors-action

**Comment by ryjones** [comment]
@arsulegai done and done!

**Pull request merged**
